include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    sort_pub_dependencies: false
    one_member_abstracts: false
    avoid_positional_boolean_parameters: false
    use_key_in_widget_constructors: false
    use_build_context_synchronously: false

