version: "3.8"
services:
  timedex-frontend:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        # Flutter files
        - ../.dart_tool:/workspace/.dart_tool:cached
        - ../.fvm:/workspace/.fvm:cached
        - ../android:/workspace/android:cached
        - ../ios:/workspace/ios:cached
        - ../lib:/workspace/lib:cached
        - ../linux:/workspace/linux:cached
        - ../macos:/workspace/macos:cached
        - ../test:/workspace/test:cached
        - ../web:/workspace/web:cached
        - ../windows:/workspace/windows:cached
        - ../.metadata:/workspace/.metadata:cached
        - ../.packages:/workspace/.packages:cached
        - ../analysis_options.yaml:/workspace/analysis_options.yaml:cached
        - ../<project_name>.iml:/workspace/<project_name>.iml:cached
        - ../pubspec.lock:/workspace/pubspec.lock:cached
        - ../pubspec.yaml:/workspace/pubspec.yaml:cached
        - ../README.md:/workspace/README.md:cached
        # VSCode settings
        - ./vscode_settings.json:/vscode_settings.json
        - ../.vscode:/workspace/.vscode:cached
        - ../lib/pages/setting/states/generated:/workspace/lib/pages/setting/states/generated:cached
      command: /bin/sh -c "while sleep 1000; do :; done"
      ports:
        - "8080:8080"
