name: time_dex
description: Flutter project
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  #framework
  go_router: ^6.2.0
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.2
  flutter_use: ^0.0.3
  state_notifier: ^0.7.2+1
  logger: ^1.3.0
  intl: ^0.18.0 #Monarch適用のためバージョン合わせ
  quiver: ^3.2.1

  device_info_plus: ^8.1.0
  flutter_keyboard_visibility_web: ^2.0.0
  url_launcher_web: ^2.0.16

  # local DataBase
  path_provider: ^2.0.13
  shared_preferences: ^2.0.18
  cupertino_icons: ^1.0.5
  flutter_secure_storage: ^8.0.0
  flutter_dotenv: ^5.0.2

  # serialization
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1

  # firebase
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.17
  firebase_analytics: ^10.1.6

  # network
  dio: ^5.0.3

  # ui components
  google_fonts: ^4.0.3
  skeleton_text: ^3.0.0
  syncfusion_flutter_calendar: ^20.4.54
  table_calendar: ^3.0.9
  flutter_advanced_switch: ^3.0.1
  fluttertoast: ^8.2.1
  flutter_quill: ^7.0.1
  dotted_border: ^2.0.0+3
  flutter_dropzone: ^3.0.5
  badges: ^3.0.2
  confetti: ^0.7.0

  # web3 package
  flutter_web3: ^2.1.9
  web3dart: ^2.6.1

  # その他BusinessLogic
  convert: ^3.1.1
  crypto: ^3.0.2
  icalendar_parser: ^1.1.1
  uuid: ^3.0.7

  # API連携
  google_sign_in: ^6.0.2
  googleapis: ^10.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.9
  
  # API definition
  openapi:
    path: ./client/



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  pedantic_mono: ^1.21.1
  freezed: ^2.3.2
  build_runner: ^2.1.11
  source_gen: ^1.2.7
  flutter_launcher_icons: ^0.12.0
  monarch: ^3.0.0

dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/logo/
    - .env
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
